apiVersion: v2
name: event-router
description: The VMware Event Router is used to connect to various VMware event providers and forwards received events to supported event processors.
home: https://vmweventbroker.io/
type: application
version: v0.7.3-pre-release
appVersion: release-0.7.2
maintainers:
  - name: Michael Gasch
    email: mgasch@vmware.com
