#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ load("@ytt:json", "json")
#@ version = json.decode(data.values.bom)["kubernetes"]["gitRepoTag"]
#@ cidr = json.decode(data.values.config)["POD_NETWORK_CIDR"]

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: #@ version
networking:
  podSubnet: #@ cidr
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: system