apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    kubernetes.io/ingress.class: contour-external
  labels:
    app: vmware
  name: event-router
  namespace: vmware-system
spec:
  routes:
  - conditions:
    - prefix: /status
    pathRewritePolicy:
      replacePrefix:
      - replacement: /status
    services:
    - name: tinywww
      port: 8100
  - conditions:
    - prefix: /bootstrap
    pathRewritePolicy:
      replacePrefix:
      - replacement: /bootstrap
    services:
    - name: tinywww
      port: 8100
  - conditions:
    - prefix: /stats
    pathRewritePolicy:
      replacePrefix:
      - replacement: /stats
    services:
    - name: vmware-event-router
      port: 8082
  - conditions:
    - prefix: /veba-ui
    services:
    - name: veba-ui
      port: 80
  virtualhost:
    fqdn: ##HOSTNAME##
    tls:
      minimumProtocolVersion: "1.2"
      secretName: ##CERT_NAME##
  includes:
  - name: sockeye
    namespace: vmware-functions
  - name: cadvisor
    namespace: vmware-system
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    kubernetes.io/ingress.class: contour-external
  name: sockeye
  namespace: vmware-functions
spec:
  routes:
  - conditions:
    - prefix: /events
    pathRewritePolicy:
      replacePrefix:
      - replacement: /
    services:
    - name: sockeye
      port: 80
  - conditions:
    - prefix: /static
    pathRewritePolicy:
      replacePrefix:
      - replacement: /static
    services:
    - name: sockeye
      port: 80
  - conditions:
    - prefix: /ws
    enableWebsockets: true
    services:
    - name: sockeye
      port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    kubernetes.io/ingress.class: contour-external
  labels:
    app: cadvisor
  name: cadvisor
  namespace: vmware-system
spec:
  routes:
  - conditions:
    - prefix: /top
    services:
    - name: cadvisor
      port: 8080