apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: veba-rabbit
  namespace: vmware-system
spec:
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
  replicas: 1
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: vmware-functions
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: veba-rabbit
    namespace: vmware-system
  delivery:
    retry: 2
    backoffPolicy: linear