name: VMware Event Router Development Build

# triggered on every push to development but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  push:
    paths:
      - "vmware-event-router/**"
    branches:
      - "development"

# run all jobs with these defaults, unless specified otherwise
defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  modules:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: verify modules are up2date/unchanged
        run: |
          make vendor
          [[ -z $(git status -s) ]] || (echo 'git dirty: modified and/or untracked'; git status -s; false)
  build-push:
    runs-on: ubuntu-latest
    needs: modules
    steps:
      - name: checkout source (this.development branch)
        uses: actions/checkout@v2
      - name: get the short commit ID
        id: get_short_commit
        run: echo ::set-output name=COMMIT::$(echo $GITHUB_SHA | cut -c -8)
      - name: log in to Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: echo "${DOCKER_SECRET}" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: test and build development image
        env:
          COMMIT: ${{ steps.get_short_commit.outputs.COMMIT }}
        run: |
          echo "Building development image for vmware-event-router with commit $COMMIT"        
          make
          docker tag vmware/veba-event-router:latest vmware/veba-event-router:$COMMIT
          docker tag vmware/veba-event-router:latest vmware/veba-event-router:development
      - name: push the development image
        env:
          COMMIT: ${{ steps.get_short_commit.outputs.COMMIT }}
        run: |
          docker push vmware/veba-event-router:$COMMIT
          docker push vmware/veba-event-router:development
